name: python_webserver
services:
  python_webserver:
    container_name: python_webserver 
    build: .
    ports:
     - 8000:8000
     - 8001:8000
    networks:
     - python_webserver_network
networks:
  python_webserver_network:
